Use craft master
getsentry/action-prepare-release pull request #22
Opened 2022-02-10 22:12 UTC by chadwhitacre

https://github.com/getsentry/publish/issues/666

2022-02-10 22:13 UTC, chadwhitacre commented
Local grep and [GH search](https://github.com/getsentry/action-prepare-release/search?q=craft_version) suggest that none of our repos are using `craft_version`.

2022-02-10 22:15 UTC, chadwhitacre commented on action.yml
> +    - uses: docker://getsentry/craft:latest
I took this from [the `publish` yaml](https://github.com/getsentry/publish/blob/737df8f68fbd4d237ff365de964a321ba0ef3bf8/.github/workflows/publish.yml#L64).

2022-02-10 22:15 UTC, chadwhitacre commented on action.yml
> -  craft_version:
Local grep and [GH search](https://github.com/getsentry/action-prepare-release/search?q=craft_version) suggest that none of our repos are using `craft_version`.

2022-02-11 11:20 UTC, kamilogorek requested changes

2022-02-11 11:20 UTC, kamilogorek commented on action.yml
> +    - uses: docker://getsentry/craft:latest
The default entrypoint for crafts docker image is `craft` binary. Without changing it, nothing will most likely(?) work, that's why its modified in the mentioned yaml - https://github.com/getsentry/publish/blob/737df8f68fbd4d237ff365de964a321ba0ef3bf8/.github/workflows/publish.yml#L66-L67

2022-02-11 12:49 UTC, BYK commented on action.yml
> -  craft_version:
Yup, I can confirm that this was added "just in case" and never got used.

2022-02-11 12:50 UTC, BYK commented on action.yml
> +    - uses: docker://getsentry/craft:latest
This will significantly slow down preparations as the Docker image is huge. Also what @kamilogorek seaid, you cannot just use `run:` etc with a custom docker image.

2022-02-11 12:51 UTC, BYK commented on action.yml
> +    - uses: docker://getsentry/craft:latest
It is a bit tricky to figure out but my recommendation would be to download the latest build artifact from Craft master instead.

2022-02-11 13:31 UTC, chadwhitacre commented on action.yml
> +    - uses: docker://getsentry/craft:latest
Thanks for the tips! :)

2022-02-11 15:03 UTC, chadwhitacre commented
> Anyone with write access to the `craft` repo can already inject code into the `publish` repo (so actually we should limit who can push to `master` on `craft` to the same set of people that can manage `publish`)

Because of this, I'm having second thoughts on the approach in this PR vs. pinning the craft version in the publish repo rather than using latest there. Maybe `action-prepare-release` could pull a version number from the `publish` repo to avoid having to set it in two places?

I don't think we want to have to lock down the `craft` repo, because it's (theoretically, at least?) not Sentry-specific. Let's locate amap of our locking-down to `publish` if we can.

2022-11-22 19:49 UTC, closed without merging