byk/build/no docker
getsentry/action-prepare-release pull request #4
Opened 2020-12-22 22:02 UTC by BYK

- wip
- feat: Run Craft outside of Docker and bundle publish request This PR bundles the 'Craft Prepare' and 'Request publish' steps by leveraging the fact that Craft can be run outside of the Docker image, w/o the Craft action as done in getsentry/sentry-javascript#3130. It also improves the automatically crated publish request issue's body by adding the comparison link, normally produced by Craft and tagging the initiator/requester of the release.

2020-12-22 22:18 UTC, chadwhitacre approved these changes
Seems reasonable, have not tested. Per commit message need to pin downstreams first to avoid inconsistency.

2020-12-23 09:36 UTC, jan-auer requested changes
**Optional Suggestion**:

Most of our repositories do not use calver, and instead a version should be required. I would add an input to toggle `calver` that defaults to off:

```yaml
inputs:
  # ...
  calver:
    description: Creates a CalVer release for the current date if no `version` is specified.
    required: false
    default: false
```

2020-12-23 09:36 UTC, jan-auer commented on action.yml
> +name: "Release prep"
_nit_: Since this is a title that shows up in every repository, it would be nice if this is not abbreviated (and title-case):

```suggestion
name: "Prepare Release"
```

2020-12-23 09:36 UTC, jan-auer commented on action.yml
> +    description: The craft version to use, defaults to latest
The `required` field is required by GitHub Actions as per [documentation](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired). It seems that the intention is that it is optional and defaults to `"latest"`.
```suggestion
    description: The craft version to use, defaults to "latest" (optional)
    required: false
    default: latest
```

2020-12-23 09:36 UTC, jan-auer commented on action.yml
> +            body: `Requested by: @${context.actor}\nView diff at: https://github.com/${repoInfo.owner}/${repoInfo.repo}/compare/${{ steps.release-branch.outputs.ref }}`
_nit_: I imagine we would be adding more body here over time. I would propose to change the output step above to:

```yaml
      run: |
        echo "::set-output name=branch::$(git rev-parse --symbolic-full-name @{-1})"
        echo "::set-output name=sha::$(git rev-parse @{-1})"
```

Then, you could format this nicer in a variable and also show a link to the check runs of the very revision:

```js
const body = `
Requested by: @${context.actor}

Quick links:
 - [View diff](https://github.com/${repoInfo.owner}/${repoInfo.repo}/compare/${{ steps.release-branch.outputs.branch }})
 - [View run](https://github.com/${repoInfo.owner}/${repoInfo.repo}/commit/${{ steps.release-branch.outputs.sha }}/checks/)
`;
```

Note that the diff link will not work after the release has been completed.

2021-01-05 21:44 UTC, BYK commented on action.yml
> +    description: The craft version to use, defaults to latest
My bad. I think we should still mark it as `required` as the default still kicks in in that case. We just don't want this to be null at any time.

2021-01-05 22:13 UTC, chadwhitacre approved these changes
Seems reasonable. Did not test. One question about an input description.

2021-01-05 22:13 UTC, chadwhitacre commented on action.yml
> +    default: latest
How do `required` and `default` interact? Is the description still accurate? "optional"?

2021-01-05 22:19 UTC, BYK commented on action.yml
> +    default: latest
Yeah, I know this is confusing. My interpretation here is:
1. `required` means it cannot be `null`
2. `default` is the value that is used when user does not provide an input

2021-01-06 09:45 UTC, jan-auer commented on action.yml
> +    default: latest
That is very confusing, thanks for clarifying 🤷‍♂️   Just to be sure -- did you test this behavior?

2021-01-06 09:46 UTC, jan-auer approved these changes

2021-01-06 10:09 UTC, BYK commented on action.yml
> +    default: latest
I did test this in earlier versions of the release action. We'll test this again today 🙂

2021-01-06 10:10 UTC, merged